### PR TITLE
fix: the issue req.URL.Host is empty

### LINKED ISSUE #56: [BUG] GetCurlCommand() can't  get  the request host
**Describe the bug**

`GetCurlCommand()` can not get the request host.

**To Reproduce**

```
package main

import (
	"fmt"
	"net/http"

	"moul.io/http2curl"
)

func greet(w http.ResponseWriter, r *http.Request) {
	command, _ := http2curl.GetCurlCommand(r)
	fmt.Fprintf(w, command.String())
}

func main() {
	http.HandleFunc("/", greet)
	http.ListenAndServe(":8080", nil)
}

```
`$ curl --location --request GET 'http://127.0.0.1:8080/'`

`Output: curl -X 'GET' -d '' -H 'Accept: */*' -H 'User-Agent: curl/7.77.0' '/'`

`Expect output:  curl -X 'GET' -d '' -H 'Accept: */*' -H 'User-Agent: curl/7.77.0' 'http://127.0.0.1:8080/'`

### PR DESCRIPTION
**Pull request by xwjdsh**
fix #56 

reference https://github.com/golang/go/issues/28940

### CODE REVIEW

**Review by moul — APPROVED** [review]

File: http2curl.go [hunk 1]
```diff
@@ -27,11 +27,25 @@ func bashEscape(str string) string {
...
 
-	if req.URL != nil && req.URL.Scheme == "https" {
+	schema := req.URL.Scheme
+	requestURL := req.URL.String()
+	if schema == "" {
+		schema = "http"
+		if req.TLS != nil {
+			schema = "https"
+		}
+		requestURL = schema + "://" + req.Host + req.URL.Path
```
Comment (morefreeze) [inline http2curl.go:45]: if only + req.URL.Path will drop query. I think if we just add default schema when schema=="", 
`requestURL = schema + "://" + requestURL` is ok

Comment (morefreeze) [reply http2curl.go:45]: Oh I see the title "the issue req.URL.Host is empty ", so we should process schema is empty and URL.host is empty separately. I'll fire another PR
